#!/usr/bin/env python3
"""Derive packages/_defaults.yml from PCWM + the owned arch policy (CW-ADR-0012).

Inputs
  docs/matrix/matrix.json               what PyTorch actually publishes (PCWM),
                                        regenerated by fetch_torch_matrix.py
  packages/_arch_policy.yml             the farm's owned per-CUDA arch policy,
                                        supported CUDA lines, python bounds

Outputs (in place)
  packages/_defaults.yml                combinations: block regenerated;
                                        header, platforms and defaults kept
  scripts/phantom_combos.json           cells our grid implies but PCWM lacks
                                        (read by generate_matrix.py)

The derivation, per (cuda, torch-minor) present in PCWM:
  - skip CUDA lines not in supported_cudas (loud warning -- wiring the
    toolkit installer is a prerequisite, see .github/actions/setup-cuda)
  - pythons = PCWM's set for the pair, clamped to [python_min, python_max]
  - pytorch = newest patch PCWM ships for the pair
  - phantom cells = (cuda, torch, python, platform) our platform axis implies
    but PCWM does not ship (e.g. cu129 torch 2.10+ has no Windows)

Exit codes: 0 unchanged, 0 changed (prints diff summary), 2 on any error.
Never run at wheel-build time -- this is a maintenance step; build output
stays a function of the git SHA (CW-ADR-0012).
"""
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
MATRIX = ROOT / "docs" / "matrix" / "matrix.json"
POLICY = ROOT / "packages" / "_arch_policy.yml"
DEFAULTS = ROOT / "packages" / "_defaults.yml"
PHANTOMS = ROOT / "scripts" / "phantom_combos.json"


def vkey(v):
    return [int(x) for x in v.split(".")]


def main() -> None:
    policy = yaml.safe_load(POLICY.read_text())
    pcwm = json.loads(MATRIX.read_text())["combos"]
    pmin, pmax = vkey(str(policy["python_min"])), vkey(str(policy["python_max"]))
    supported = [str(c) for c in policy["supported_cudas"]]
    platforms = policy["platforms"]

    # Collect PCWM cells. Rows (torch patches, python sets) derive from the
    # x86 cells; aarch64 cells are tracked separately so packages that opt
    # into the linux_aarch64 platform get phantoms for upstream's ragged ARM
    # coverage (e.g. cu126 skipped torch 2.7/2.8 on aarch64 entirely).
    pairs: dict[tuple, dict] = {}
    for c in pcwm:
        cuda_dotted = f"{c['cuda'][2:-1]}.{c['cuda'][-1]}"
        minor = ".".join(c["torch"].split(".")[:2])
        if "aarch64" in c["platform"]:
            pairs.setdefault((cuda_dotted, minor),
                             {"patches": set(), "cells": set()})["cells"].add(
                (c["python"], "linux_aarch64"))
            continue
        p = pairs.setdefault((cuda_dotted, minor),
                             {"patches": set(), "cells": set()})
        p["patches"].add(c["torch"])
        plat = "windows" if "win" in c["platform"] else "linux"
        p["cells"].add((c["python"], plat))

    skipped_cudas = sorted({cu for cu, _ in pairs} - set(supported), key=vkey)
    for cu in skipped_cudas:
        n = sum(1 for (c, _m) in pairs if c == cu)
        print(f"WARNING: PCWM ships cu{cu.replace('.', '')} ({n} torch minors) but "
              f"it is not in supported_cudas -- wire the toolkit installer in "
              f".github/actions/setup-cuda, then add it to packages/_arch_policy.yml",
              file=sys.stderr)

    rows, phantoms = [], []
    for (cuda, minor) in sorted(pairs, key=lambda k: (vkey(k[0]), vkey(k[1]))):
        if cuda not in supported:
            continue
        info = pairs[(cuda, minor)]
        if not info["patches"]:
            continue  # aarch64-only pairing; no x86 torch to pin a row on
        pys = sorted({py for py, plat in info["cells"] if plat != "linux_aarch64"
                      and pmin <= vkey(py) <= pmax}, key=vkey)
        if not pys:
            continue
        rows.append({
            "cuda": cuda,
            "pytorch": max(info["patches"], key=vkey),
            "python_versions": pys,
        })
        for py in pys:
            for plat in platforms + ["linux_aarch64"]:
                key = plat if plat in ("windows", "linux_aarch64") else "linux"
                if (py, key) not in info["cells"]:
                    phantoms.append([cuda.replace(".", ""), minor,
                                     py.replace(".", ""), plat])

    # Splice the combinations block; keep everything else in the file.
    text = DEFAULTS.read_text()
    m = re.search(r"^combinations:\n(.*?)(?=^platforms:)", text, re.M | re.S)
    if not m:
        raise SystemExit("ERROR: could not locate combinations block in _defaults.yml")
    block = ["combinations:",
             "  # CELLS ONLY, derived by scripts/derive_defaults.py from",
             "  # docs/matrix/matrix.json (PCWM). Arch lists live in",
             "  # packages/_arch_policy.yml, read at build time. Do not",
             "  # hand-edit rows; re-run the script."]
    cur = None
    for r in rows:
        if r["cuda"] != cur:
            cur = r["cuda"]
            block.append(f"  # ── cu{cur.replace('.', '')} ──")
        pyl = ", ".join(f'"{p}"' for p in r["python_versions"])
        block.append(f'  - cuda: "{r["cuda"]}"')
        block.append(f'    pytorch: "{r["pytorch"]}"')
        block.append(f"    python_versions: [{pyl}]")
    new_text = text[:m.start()] + "\n".join(block) + "\n\n" + text[m.end():]

    old_rows = yaml.safe_load(text)["combinations"]
    changed = yaml.safe_load(new_text)["combinations"] != old_rows
    DEFAULTS.write_text(new_text)
    PHANTOMS.write_text(json.dumps(
        {"_comment": "Cells the grid implies but PCWM does not ship (CW-ADR-0007). "
                     "Generated by derive_defaults.py; read by generate_matrix.py.",
         "combos": sorted(phantoms)}, indent=1) + "\n")

    print(f"{len(rows)} rows ({len(old_rows)} before, "
          f"{'CHANGED' if changed else 'unchanged'}), "
          f"{len(phantoms)} phantom cells, "
          f"{len(skipped_cudas)} unsupported CUDA line(s) skipped: {skipped_cudas}")


if __name__ == "__main__":
    main()
